name: "Subir archivos a nube de nexus"
description: "Subir archivos a nube de nexus"
inputs:
    server-url:
      description: "URL del servidor de Nexus"
      required: true
    username:
      description: "Nombre de usuario"
      required: true
    password:
      description: "Contraseña"
      required: true
    repository:
      description: "Nombre del repositorio"
      required: true
    file:
      description: "Nombre del archivo a subir"
      required: true 
runs:
  upload-raw:
    steps:
    - name: upload
      run: curl -v -u "${{ inputs.username }}:${{ inputs.password }}" --upload-file ${{ inputs.file }} ${{ inputs.server-url }}/repository/${{ inputs.repository }}/${{ inputs.file }}
  
  