name: "Subir archivos a nube de nexus"
author: "Javier"
description: "Subir archivos a nube de nexus"
inputs:
    server-url:
      description: "URL del servidor de Nexus"
      required: true
    username:
      description: "Nombre de usuario"
      required: true
    password:
      description: "Contraseña"
      required: true
    repository:
      description: "Nombre del repositorio"
      required: true
    file:
      description: "Nombre del archivo a subir"
      required: true 
jobs:
  upload-raw:
    steps:
    - name: upload
      run: curl -v --user '${{ secrets.USER_NEXUS }}:${{ secrets.NEXUS_PASS }}' --upload-file archivo.txt https://nexus.prisamedia.com/repository/raw-test/archivo.txt
  
  