name: "Subir archivos a nube de nexus"
description: "Subir archivos a nube de nexus"
inputs:
    server-url:
      description: "URL del servidor de Nexus"
      required: true
    username:
      description: "Nombre de usuario"
      required: true
    password:
      description: "Contraseña"
      required: true
    repository:
      description: "Nombre del repositorio"
      required: true
    file:
      description: "Nombre del archivo a subir"
      required: true 
    format:
      description: "Tipo de repositorio al que se va a subir el artefacto"
      requiered: true

runs:
  using: 'composite'
  steps:

    - name: repo-default
      run: |
        curl -v -u "${{ inputs.username }}:${{ inputs.password }}" --upload-file ${{ inputs.file }} ${{ inputs.server-url }}/repository/${{ inputs.repository }}/${{ inputs.file }};
        status=$(curl -v -u "${{ inputs.username }}:${{ inputs.password }}" -o /dev/null -s -w "%{http_code}" ${{ inputs.server-url }}/repostory/${{ inputs.repository }}/${{ inputs.file }});
        if [ "$status" -ge 200 ] && [ "$status" -lt 300 ]
        then
          echo "El fichero se ha subido correctamente"
        else
          echo "El fichero no se ha subido correctamente"
          exit 1
        fi
      if: ${{ inputs.format == 'raw' }}
      shell: bash

